C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1smeAXDNP0_3(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 M3
      REAL*8 P3(0:3)
      COMPLEX*16 V3(6)
      REAL*8 W3
      COMPLEX*16 DENOM


      COMPLEX*16 tmp28
      COMPLEX*16 tmp29
      COMPLEX*16 tmp30
      COMPLEX*16 tmp31

      COMPLEX*16 ca00
      COMPLEX*16 ca01
      COMPLEX*16 ca02
      COMPLEX*16 ca03
      COMPLEX*16 ca10
      COMPLEX*16 ca11
      COMPLEX*16 ca12
      COMPLEX*16 ca13
      COMPLEX*16 ca20
      COMPLEX*16 ca21
      COMPLEX*16 ca22
      COMPLEX*16 ca23
      COMPLEX*16 ca30
      COMPLEX*16 ca31
      COMPLEX*16 ca32
      COMPLEX*16 ca33


C   Define the sme coefficients

      ca00 = (0D0,0D0)
      ca01 = (1.01D0,-0.5D0)
      ca02 = (0D0,0D0)
      ca03 = (0D0,0D0)
      ca10 = (1.01D0,0.5D0)
      ca11 = (0D0,0D0)
      ca12 = (-1.04D0,-0.37D0)
      ca13 = (0D0,0D0)
      ca20 = (0D0,0.0D0)
      ca21 = (-1.04D0,0.37D0)
      ca22 = (0D0,0D0)
      ca23 = (0D0,0D0)
      ca30 = (0D0,0.0D0)
      ca31 = (0D0,0.0D0)
      ca32 = (0D0,0.0D0)
      ca33 = (0D0,0D0)


      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))


      tmp28 = ca00*F1(3)-ca01*F1(4)-ca02*F1(5)-ca03*F1(6);
      tmp29= ca10*F1(3)-ca11*F1(4)-ca12*F1(5)-ca13*F1(6);
      tmp30= ca20*F1(3)-ca21*F1(4)-ca22*F1(5)-ca23*F1(6);
      tmp31= ca30*F1(3)-ca31*F1(4)-ca32*F1(5)-ca33*F1(6);


      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
   
      V3(3) = DENOM*(0.5D0)*CI*(tmp30*F2(3)+tmp31*F2(4)-tmp28*F2(5)
     $-tmp29*F2(6))

      V3(4) = DENOM*(0.5D0)*CI*(tmp31*F2(3)+tmp30*F2(4)+tmp29*F2(5)
     $ +tmp28*F2(6))

      V3(5) = DENOM*(0.5D0)*CI*(-CI*tmp31*F2(3)+CI*tmp30*F2(4)
     $-CI*tmp29*F2(5)+CI*tmp28*F2(6))

      V3(6) = DENOM*(0.5D0)*CI*(tmp30*F2(3)-tmp31*F2(4)+tmp28*F2(5)
     $-tmp29*F2(6))


      END


      SUBROUTINE FFV1smeAXDNP1N_3(F1, F2, COUP,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(6)

      COMPLEX*16 tmp4
      COMPLEX*16 tmp5
      COMPLEX*16 tmp6
      COMPLEX*16 tmp7

      COMPLEX*16 ca00
      COMPLEX*16 ca01
      COMPLEX*16 ca02
      COMPLEX*16 ca03
      COMPLEX*16 ca10
      COMPLEX*16 ca11
      COMPLEX*16 ca12
      COMPLEX*16 ca13
      COMPLEX*16 ca20
      COMPLEX*16 ca21
      COMPLEX*16 ca22
      COMPLEX*16 ca23
      COMPLEX*16 ca30
      COMPLEX*16 ca31
      COMPLEX*16 ca32
      COMPLEX*16 ca33


C   Define the sme coefficients

      ca00 = (0D0,0D0)
      ca01 = (1.01D0,-0.5D0)
      ca02 = (0D0,0D0)
      ca03 = (0D0,0D0)
      ca10 = (1.01D0,0.5D0)
      ca11 = (0D0,0D0)
      ca12 = (-1.04D0,-0.37D0)
      ca13 = (0D0,0D0)
      ca20 = (0D0,0.0D0)
      ca21 = (-1.04D0,0.37D0)
      ca22 = (0D0,0D0)
      ca23 = (0D0,0D0)
      ca30 = (0D0,0.0D0)
      ca31 = (0D0,0.0D0)
      ca32 = (0D0,0.0D0)
      ca33 = (0D0,0D0)
      
      tmp4 = -F1(6)*F2(3) + F1(5)*F2(4) - F1(4)*F2(5) + F1(3)*F2(6)
      tmp5 =F1(6)*F2(3) + F1(5)*F2(4) + F1(4)*F2(5) + F1(3)*F2(6)
      tmp6 = F1(5)*F2(3) + F1(6)*F2(4) - F1(3)*F2(5) - F1(4)*F2(6)
      tmp7 = F1(5)*F2(3) - F1(6)*F2(4) + F1(3)*F2(5) - F1(4)*F2(6)


      V3(3)= COUP*(-0.5D0)*(CI)*(CI*ca20*tmp4+ca10*tmp5+ca00*tmp6+ca30*tmp7)
      V3(4)= COUP*(-0.5D0)*(CI)*(CI*ca21*tmp4+ca11*tmp5+ca01*tmp6+ca31*tmp7)
      V3(5)= COUP*(-0.5D0)*(CI)*(CI*ca22*tmp4+ca12*tmp5+ca02*tmp6+ca32*tmp7)
      V3(6)= COUP*(-0.5D0)*(CI)*(CI*ca23*tmp4+ca13*tmp5+ca03*tmp6+ca33*tmp7)
      END

















