C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1smeVEUP_2(F1, V3, COUP, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      REAL*8 M2
      REAL*8 P2(0:3)
      COMPLEX*16 V3(*)
      REAL*8 W2
      COMPLEX*16 DENOM

      COMPLEX*16 tmp8
      COMPLEX*16 tmp9
      COMPLEX*16 tmp10
      COMPLEX*16 tmp11
      COMPLEX*16 tmp20
      COMPLEX*16 tmp21
      COMPLEX*16 tmp22
      COMPLEX*16 tmp23

      COMPLEX*16 cv00
      COMPLEX*16 cv01
      COMPLEX*16 cv02
      COMPLEX*16 cv03
      COMPLEX*16 cv10
      COMPLEX*16 cv11
      COMPLEX*16 cv12
      COMPLEX*16 cv13
      COMPLEX*16 cv20
      COMPLEX*16 cv21
      COMPLEX*16 cv22
      COMPLEX*16 cv23
      COMPLEX*16 cv30
      COMPLEX*16 cv31
      COMPLEX*16 cv32
      COMPLEX*16 cv33

C   Define the sme coefficients

      cv00 = (0D0,0D0)
      cv01 = (-0.79D0,-0.43D0)
      cv02 = (0D0,0D0)
      cv03 = (0D0,0D0)
      cv10 = (-0.79D0,0.43D0)
      cv11 = (0D0,0D0)
      cv12 = (0.06D0,0.18D0)
      cv13 = (0D0,0D0)
      cv20 = (0D0,-0.0D0)
      cv21 = (0.06D0,-0.18D0)
      cv22 = (0D0,0D0)
      cv23 = (0D0,0D0)
      cv30 = (0D0,-0.0D0)
      cv31 = (0D0,-0.0D0)
      cv32 = (0D0,-0.0D0)
      cv33 = (0D0,0D0)


      F2(1) = +F1(1)+V3(1)
      F2(2) = +F1(2)+V3(2)
      P2(0) = -DBLE(F2(1))
      P2(1) = -DBLE(F2(2))
      P2(2) = -DIMAG(F2(2))
      P2(3) = -DIMAG(F2(1))

C   Define some tmp variables

      tmp8=cv00*V3(3)+cv01*V3(4)+cv02*V3(5)+cv03*V3(6)
      tmp9=cv10*V3(3)+cv11*V3(4)+cv12*V3(5)+cv13*V3(6)
      tmp10=cv20*V3(3)+cv21*V3(4)+cv22*V3(5)+cv23*V3(6)
      tmp11=cv30*V3(3)+cv31*V3(4)+cv32*V3(5)+cv33*V3(6)

      tmp20=P2(0)+P2(3)
      tmp21=P2(0)-P2(3)
      tmp22=P2(1)+CI*P2(2)
      tmp23=P2(1)-CI*P2(2)

      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
    
      F2(3) = DENOM*(0.5D0)*( 
     $ (CI*tmp9*tmp23+CI*tmp8*tmp21-CI*tmp11*tmp21-tmp10*tmp23)*F1(3)
     $ +(-CI*tmp8*tmp23-CI*tmp11*tmp23-CI*tmp9*tmp21-tmp10*tmp21)*F1(4)
     $ +CI*(tmp8+tmp11)*M2*F1(5)+(tmp10+CI*tmp9)*M2*F1(6))

      F2(4) = DENOM*(0.5D0)*( 
     $ (CI*tmp11*tmp22-CI*tmp8*tmp22-CI*tmp9*tmp20+tmp10*tmp20)*F1(3)
     $ +(CI*tmp9*tmp22+tmp10*tmp22+CI*tmp8*tmp20+CI*tmp11*tmp20)*F1(4)
     $ +M2*(CI*tmp9-tmp10)*F1(5)+ CI*(tmp8-tmp11)*M2*F1(6))

      F2(5) = DENOM*(0.5D0)*( 
     $ CI*(tmp8-tmp11)*M2*F1(3)+M2*(-CI*tmp9-tmp10)*F1(4)
     $ +(-tmp10*tmp23+CI*tmp9*tmp23+CI*tmp8*tmp20+CI*tmp11*tmp20)*F1(5)
     $+(-CI*tmp11*tmp23+CI*tmp8*tmp23+CI*tmp9*tmp20+tmp10*tmp20)*F1(6))

      F2(6) = DENOM*(0.5D0)*( 
     $ (tmp10-CI*tmp9)*M2*F1(3)+CI*(tmp8+tmp11)*M2*F1(4)
     $ +(CI*tmp8*tmp22+CI*tmp11*tmp22+CI*tmp9*tmp21-tmp10*tmp21)*F1(5)
     $ +(CI*tmp9*tmp22+tmp10*tmp22+CI*tmp8*tmp21-CI*tmp11*tmp21)*F1(6))

      END



      SUBROUTINE FFV1smeVEUPP1N_2(F1, V3, COUP,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 V3(*)

      COMPLEX*16 tmp8
      COMPLEX*16 tmp9
      COMPLEX*16 tmp10
      COMPLEX*16 tmp11

      COMPLEX*16 cv00
      COMPLEX*16 cv01
      COMPLEX*16 cv02
      COMPLEX*16 cv03
      COMPLEX*16 cv10
      COMPLEX*16 cv11
      COMPLEX*16 cv12
      COMPLEX*16 cv13
      COMPLEX*16 cv20
      COMPLEX*16 cv21
      COMPLEX*16 cv22
      COMPLEX*16 cv23
      COMPLEX*16 cv30
      COMPLEX*16 cv31
      COMPLEX*16 cv32
      COMPLEX*16 cv33

C   Define the sme coefficients

      cv00 = (0D0,0D0)
      cv01 = (-0.79D0,-0.43D0)
      cv02 = (0D0,0D0)
      cv03 = (0D0,0D0)
      cv10 = (-0.79D0,0.43D0)
      cv11 = (0D0,0D0)
      cv12 = (0.06D0,0.18D0)
      cv13 = (0D0,0D0)
      cv20 = (0D0,-0.0D0)
      cv21 = (0.06D0,-0.18D0)
      cv22 = (0D0,0D0)
      cv23 = (0D0,0D0)
      cv30 = (0D0,-0.0D0)
      cv31 = (0D0,-0.0D0)
      cv32 = (0D0,-0.0D0)
      cv33 = (0D0,0D0)

C   Define some tmp variables

      tmp8=cv00*V3(3)+cv01*V3(4)+cv02*V3(5)+cv03*V3(6)
      tmp9=cv10*V3(3)+cv11*V3(4)+cv12*V3(5)+cv13*V3(6)
      tmp10=cv20*V3(3)+cv21*V3(4)+cv22*V3(5)+cv23*V3(6)
      tmp11=cv30*V3(3)+cv31*V3(4)+cv32*V3(5)+cv33*V3(6)


      F2(3)= COUP*(0.5D0)*(-CI)*((tmp8+tmp11)*F1(5)+(tmp9-CI*tmp10)*F1(6))
      F2(4)= COUP*(0.5D0)*(-CI)*((tmp9+CI*tmp10)*F1(5)+(tmp8-tmp11)*F1(6))
      F2(5)= COUP*(0.5D0)*(-CI)*((tmp8-tmp11)*F1(3)+(-tmp9+CI*tmp10)*F1(4))
      F2(6)= COUP*(0.5D0)*(-CI)*((-tmp9-CI*tmp10)*F1(3)+(tmp8+tmp11)*F1(4))
      END




  


  

