C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1smeAXUP_2(F1, V3, COUP, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      REAL*8 M2
      REAL*8 P2(0:3)
      COMPLEX*16 V3(*)
      REAL*8 W2
      COMPLEX*16 DENOM

      COMPLEX*16 tmp12
      COMPLEX*16 tmp13
      COMPLEX*16 tmp14
      COMPLEX*16 tmp15
      COMPLEX*16 tmp20
      COMPLEX*16 tmp21
      COMPLEX*16 tmp22
      COMPLEX*16 tmp23

      COMPLEX*16 ca00
      COMPLEX*16 ca01
      COMPLEX*16 ca02
      COMPLEX*16 ca03
      COMPLEX*16 ca10
      COMPLEX*16 ca11
      COMPLEX*16 ca12
      COMPLEX*16 ca13
      COMPLEX*16 ca20
      COMPLEX*16 ca21
      COMPLEX*16 ca22
      COMPLEX*16 ca23
      COMPLEX*16 ca30
      COMPLEX*16 ca31
      COMPLEX*16 ca32
      COMPLEX*16 ca33

C   Define the sme coefficients

      ca00 = (0D0,0D0)
      ca01 = (0.05D0,-0.43D0)
      ca02 = (0D0,0D0)
      ca03 = (0D0,0D0)
      ca10 = (0.05D0,0.43D0)
      ca11 = (0D0,0D0)
      ca12 = (-1.88D0,0.72D0)
      ca13 = (0D0,0D0)
      ca20 = (0D0,0.0D0)
      ca21 = (-1.88D0,-0.72D0)
      ca22 = (0D0,0D0)
      ca23 = (0D0,0D0)
      ca30 = (0D0,0.0D0)
      ca31 = (0D0,0.0D0)
      ca32 = (0D0,0.0D0)
      ca33 = (0D0,0D0)


      F2(1) = +F1(1)+V3(1)
      F2(2) = +F1(2)+V3(2)
      P2(0) = -DBLE(F2(1))
      P2(1) = -DBLE(F2(2))
      P2(2) = -DIMAG(F2(2))
      P2(3) = -DIMAG(F2(1))

C   Define some tmp variables

      tmp12=ca00*V3(3)+ca01*V3(4)+ca02*V3(5)+ca03*V3(6)
      tmp13=ca10*V3(3)+ca11*V3(4)+ca12*V3(5)+ca13*V3(6)
      tmp14=ca20*V3(3)+ca21*V3(4)+ca22*V3(5)+ca23*V3(6)
      tmp15=ca30*V3(3)+ca31*V3(4)+ca32*V3(5)+ca33*V3(6)
      
      tmp20=P2(0)+P2(3)
      tmp21=P2(0)-P2(3)
      tmp22=P2(1)+CI*P2(2)
      tmp23=P2(1)-CI*P2(2)



      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
    
      F2(3) = DENOM*(0.5D0)*( 
     $ (-CI*tmp13*tmp23+tmp14*tmp23-CI*tmp12*tmp21+CI*tmp15*tmp21)*F1(3)
     $ +(CI*tmp12*tmp23+CI*tmp15*tmp23+CI*tmp13*tmp21+tmp14*tmp21)*F1(4)
     $ +CI*(tmp12+tmp15)*M2*F1(5)+(tmp14+CI*tmp13)*M2*F1(6))

      F2(4) = DENOM*(0.5D0)*( 
     $ (CI*tmp12*tmp22-CI*tmp15*tmp22+CI*tmp13*tmp20-tmp14*tmp20)*F1(3)
     $ +(-tmp14*tmp22-CI*tmp13*tmp22-CI*tmp12*tmp20-CI*tmp15*tmp20)*F1(4)
     $ +M2*(CI*tmp13-tmp14)*F1(5)+CI*(tmp12-tmp15)*M2*F1(6))

      F2(5) = DENOM*(0.5D0)*( 
     $ M2*CI*(-tmp12+tmp15)*F1(3)+(tmp14+CI*tmp13)*M2*F1(4)
     $ +(-tmp14*tmp23+CI*tmp13*tmp23+CI*tmp12*tmp20+CI*tmp15*tmp20)*F1(5)
     $ +(-CI*tmp15*tmp23+CI*tmp12*tmp23+CI*tmp13*tmp20+tmp14*tmp20)*F1(6))

      F2(6) = DENOM*(0.5D0)*( 
     $ M2*(CI*tmp13-tmp14)*F1(3)-CI*(tmp12+tmp15)*M2*F1(4)
     $+(CI*tmp12*tmp22+CI*tmp15*tmp22+CI*tmp13*tmp21-tmp14*tmp21)*F1(5)
     $+(CI*tmp13*tmp22+tmp14*tmp22+CI*tmp12*tmp21-CI*tmp15*tmp21)*F1(6))

      END



      SUBROUTINE FFV1smeAXUPP1N_2(F1, V3, COUP,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 V3(*)

      COMPLEX*16 tmp12
      COMPLEX*16 tmp13
      COMPLEX*16 tmp14
      COMPLEX*16 tmp15

      COMPLEX*16 ca00
      COMPLEX*16 ca01
      COMPLEX*16 ca02
      COMPLEX*16 ca03
      COMPLEX*16 ca10
      COMPLEX*16 ca11
      COMPLEX*16 ca12
      COMPLEX*16 ca13
      COMPLEX*16 ca20
      COMPLEX*16 ca21
      COMPLEX*16 ca22
      COMPLEX*16 ca23
      COMPLEX*16 ca30
      COMPLEX*16 ca31
      COMPLEX*16 ca32
      COMPLEX*16 ca33

C   Define the sme coefficients

      ca00 = (0D0,0D0)
      ca01 = (0.05D0,-0.43D0)
      ca02 = (0D0,0D0)
      ca03 = (0D0,0D0)
      ca10 = (0.05D0,0.43D0)
      ca11 = (0D0,0D0)
      ca12 = (-1.88D0,0.72D0)
      ca13 = (0D0,0D0)
      ca20 = (0D0,0.0D0)
      ca21 = (-1.88D0,-0.72D0)
      ca22 = (0D0,0D0)
      ca23 = (0D0,0D0)
      ca30 = (0D0,0.0D0)
      ca31 = (0D0,0.0D0)
      ca32 = (0D0,0.0D0)
      ca33 = (0D0,0D0)

C   Define some tmp variables

      tmp12=ca00*V3(3)+ca01*V3(4)+ca02*V3(5)+ca03*V3(6)
      tmp13=ca10*V3(3)+ca11*V3(4)+ca12*V3(5)+ca13*V3(6)
      tmp14=ca20*V3(3)+ca21*V3(4)+ca22*V3(5)+ca23*V3(6)
      tmp15=ca30*V3(3)+ca31*V3(4)+ca32*V3(5)+ca33*V3(6)

      F2(3)= COUP*(0.5D0)*(-CI)*((tmp12+tmp15)*F1(5)+(tmp13-CI*tmp14)*F1(6))
      F2(4)= COUP*(0.5D0)*(-CI)*((tmp13+CI*tmp14)*F1(5)+(tmp12-tmp15)*F1(6))
      F2(5)= COUP*(0.5D0)*(-CI)*((-tmp12+tmp15)*F1(3)+(tmp13-CI*tmp14)*F1(4))
      F2(6)= COUP*(0.5D0)*(-CI)*((tmp13+CI*tmp14)*F1(3)+(-tmp12-tmp15)*F1(4))
      END










  


  

