C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1smeAXUP_0(F1, F2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMPV
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX

      COMPLEX*16 tmp4
      COMPLEX*16 tmp5
      COMPLEX*16 tmp6
      COMPLEX*16 tmp7
      COMPLEX*16 tmp12
      COMPLEX*16 tmp13
      COMPLEX*16 tmp14
      COMPLEX*16 tmp15

      COMPLEX*16 ca00
      COMPLEX*16 ca01
      COMPLEX*16 ca02
      COMPLEX*16 ca03
      COMPLEX*16 ca10
      COMPLEX*16 ca11
      COMPLEX*16 ca12
      COMPLEX*16 ca13
      COMPLEX*16 ca20
      COMPLEX*16 ca21
      COMPLEX*16 ca22
      COMPLEX*16 ca23
      COMPLEX*16 ca30
      COMPLEX*16 ca31
      COMPLEX*16 ca32
      COMPLEX*16 ca33

C   Define the sme coefficients

      ca00 = (0D0,0D0)
      ca01 = (0.05D0,-0.43D0)
      ca02 = (0D0,0D0)
      ca03 = (0D0,0D0)
      ca10 = (0.05D0,0.43D0)
      ca11 = (0D0,0D0)
      ca12 = (-1.88D0,0.72D0)
      ca13 = (0D0,0D0)
      ca20 = (0D0,0.0D0)
      ca21 = (-1.88D0,-0.72D0)
      ca22 = (0D0,0D0)
      ca23 = (0D0,0D0)
      ca30 = (0D0,0.0D0)
      ca31 = (0D0,0.0D0)
      ca32 = (0D0,0.0D0)
      ca33 = (0D0,0D0)

C   Define some tmp variables

      tmp4 = (-1D0)*F1(6)*F2(3) + F1(5)*F2(4) - F1(4)*F2(5) + F1(3)*F2(6)
      tmp5 =  F1(6)*F2(3) + F1(5)*F2(4) + F1(4)*F2(5) + F1(3)*F2(6)
      tmp6 =  F1(5)*F2(3) + F1(6)*F2(4) - F1(3)*F2(5) - F1(4)*F2(6)
      tmp7 =  F1(5)*F2(3) - F1(6)*F2(4) + F1(3)*F2(5) - F1(4)*F2(6)

      tmp12=ca00*V3(3)+ca01*V3(4)+ca02*V3(5)+ca03*V3(6)
      tmp13=ca10*V3(3)+ca11*V3(4)+ca12*V3(5)+ca13*V3(6)
      tmp14=ca20*V3(3)+ca21*V3(4)+ca22*V3(5)+ca23*V3(6)
      tmp15=ca30*V3(3)+ca31*V3(4)+ca32*V3(5)+ca33*V3(6)


      TMPV = (0.5D0)*((CI)*tmp4*tmp14 + tmp5*tmp13 + tmp6*tmp12 + tmp7*tmp15)

      VERTEX = COUP*(-CI * TMPV)
      END